### ISSUE TITLE
editing the values of the fixed frequncies

### ISSUE THREAD

**Issue by Mood-al** [rohansohonee/equalizer#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mood-al** [comment]
hi there i would like to change these fixed values that appears in the image  to other values that i can choose but as i saw that you cant do that in the package so i dont know if there is anything that i can do to change them 
![image](https://user-images.githubusercontent.com/63562308/104821248-fb810a80-5853-11eb-960f-b9e6e6f41c2c.png)

**Comment by tharun634** [comment]
I think the Android's Equaliser engine has the fixed bands 
[source](https://developer.android.com/reference/android/media/audiofx/Equalizer#PARAM_NUM_BANDS)

**Comment by rohansohonee** [comment]
> I think the Android's Equaliser engine has the fixed bands
[source](https://developer.android.com/reference/android/media/audiofx/Equalizer#PARAM_NUM_BANDS)

Yes.
