### ISSUE TITLE
Please add Null Safety.

### ISSUE THREAD

**Issue by mike1985dev** [rohansohonee/equalizer#9]
Can you add Null Safety please and thank you!

**Comment by felipecastrosales** [comment]
News about this, @rohansohonee? It would be amazing. :D

**Comment by rohansohonee** [comment]
Hi

You check this PR #6 and implement the changes as described in my comment. "NOTE: I have not tested this."

I am not maintaining this project at the moment. I will update the README file and refer to another package which already provides equalizer functionality and is available for iOS platform.
See https://github.com/ryanheise/just_audio/issues/147
